import { Node, FileNode } from './types';

export const INITIAL_DATA: Node[] = [
  // Top Level Folders
  { id: 'f-concepts', name: 'Messianic Concepts | מושגים וערכים', type: 'folder', parentId: null, createdAt: Date.now() },
  { id: 'f-belief', name: 'Belief & Anticipation | אמונה וציפייה', type: 'folder', parentId: null, createdAt: Date.now() - 10 },
  { id: 'f-destinies', name: 'Redemptive Prophecies | יעודי הגאולה', type: 'folder', parentId: null, createdAt: Date.now() - 20 },
  { id: 'f-sages', name: 'Teachings of the Sages | ילקוט ביאורי חז"ל', type: 'folder', parentId: null, createdAt: Date.now() - 30 },
  { id: 'f-notes', name: 'Scholarly Insights | הערות וביאורים', type: 'folder', parentId: null, createdAt: Date.now() - 40 },
  { id: 'f-rambam', name: 'Maimonides Studies | ביאורי הרמב"ם', type: 'folder', parentId: null, createdAt: Date.now() - 50 },
  { id: 'f-seforim', name: 'The Classic Library | אוצר הספרים', type: 'folder', parentId: null, createdAt: Date.now() - 60 },
  { id: 'f-videos', name: 'Multimedia Archive | תיעוד ומדיה', type: 'folder', parentId: null, createdAt: Date.now() - 70 },

  // Subfolders
  { id: 'sf-seforim-portals', name: 'Digital Libraries | ספריות דיגיטליות', type: 'folder', parentId: 'f-seforim', createdAt: Date.now() - 71 },
  { id: 'sf-seforim-list', name: 'Seforim Archive | ארכיון ספרים', type: 'folder', parentId: 'f-seforim', createdAt: Date.now() - 72 },
  { id: 'sf-articles-deep', name: 'Articles & Deep Dives | מאמרים ועיונים', type: 'folder', parentId: 'f-videos', createdAt: Date.now() - 73 }, // Keeping for now, might be repurposed
  { id: 'sf-portals', name: 'Video Portals | פורטלי וידאו', type: 'folder', parentId: 'f-videos', createdAt: Date.now() - 74 }, // Keeping for now, might be repurposed
  { id: 'sf-new-torah', name: 'The New Torah | תורה חדשה', type: 'folder', parentId: 'f-concepts', createdAt: Date.now() - 80 },
  { id: 'sf-elijah', name: 'Prophet Elijah | עניני אליהו הנביא', type: 'folder', parentId: 'f-concepts', createdAt: Date.now() - 90 },
  { id: 'sf-rambam-12', name: 'Chapter 12 | הלכות מלכים פרק י"ב', type: 'folder', parentId: 'f-rambam', createdAt: Date.now() - 100 },
  { id: 'sf-rambam-11', name: 'Chapter 11 | הלכות מלכים פרק י"א', type: 'folder', parentId: 'f-rambam', createdAt: Date.now() - 110 },

  // NEW FOLDERS derived from paths
  { id: 'sf-concepts-belief', name: 'Belief & Anticipation | אמונה וציפייה', type: 'folder', parentId: 'f-concepts', createdAt: Date.now() - 120 },
  { id: 'sf-concepts-eli', name: 'Prophet Elijah | עניני אליהו הנביא', type: 'folder', parentId: 'f-concepts', createdAt: Date.now() - 121 },
  { id: 'sf-concepts-new-torah', name: 'New Torah | תורה חדשה', type: 'folder', parentId: 'f-concepts', createdAt: Date.now() - 122 },
  { id: 'sf-rambam-11-h1', name: 'Halacha 1 | הלכה א', type: 'folder', parentId: 'sf-rambam-11', createdAt: Date.now() - 123 },
  { id: 'sf-rambam-11-h2', name: 'Halacha 2 | הלכה ב', type: 'folder', parentId: 'sf-rambam-11', createdAt: Date.now() - 124 },
  { id: 'sf-rambam-11-h3', name: 'Halacha 3 | הלכה ג', type: 'folder', parentId: 'sf-rambam-11', createdAt: Date.now() - 125 },
  { id: 'sf-rambam-11-h4', name: 'Halacha 4 | הלכה ד', type: 'folder', parentId: 'sf-rambam-11', createdAt: Date.now() - 126 },
  { id: 'sf-rambam-12-h2', name: 'Halacha 2 | הלכה ב', type: 'folder', parentId: 'sf-rambam-12', createdAt: Date.now() - 127 },
  { id: 'sf-sages-quotes', name: 'Sayings of the Sages | מאמרי חז"ל', type: 'folder', parentId: 'f-sages', createdAt: Date.now() - 128 },
  { id: 'sf-notes-general', name: 'General Notes | הערות כלליות', type: 'folder', parentId: 'f-notes', createdAt: Date.now() - 129 },
  { id: 'sf-destinies-general', name: 'General Prophecies | יעודים כלליים', type: 'folder', parentId: 'f-destinies', createdAt: Date.now() - 130 },
  { id: 'sf-seforim-by-topic', name: 'By Topic | לפי נושאים', type: 'folder', parentId: 'f-seforim', createdAt: Date.now() - 131 },
  { id: 'sf-seforim-classics', name: 'Classics | ספרי יסוד', type: 'folder', parentId: 'sf-seforim-by-topic', createdAt: Date.now() - 132 },
  { id: 'sf-seforim-kabbalah', name: 'Kabbalah | ספרי קבלה', type: 'folder', parentId: 'sf-seforim-by-topic', createdAt: Date.now() - 133 },
  { id: 'sf-seforim-midrashim', name: 'Midrashim | מדרשי חז"ל', type: 'folder', parentId: 'sf-seforim-by-topic', createdAt: Date.now() - 134 },
  { id: 'sf-seforim-tanach', name: 'Tanach | תורה שבכתב', type: 'folder', parentId: 'sf-seforim-by-topic', createdAt: Date.now() - 135 },
  { id: 'sf-seforim-third-beit-hamikdash', name: 'Third Beis Hamikdosh | בית המקדש השלישי', type: 'folder', parentId: 'sf-seforim-by-topic', createdAt: Date.now() - 136 },
  { id: 'sf-seforim-basics', name: 'Basics | כללי', type: 'folder', parentId: 'sf-seforim-by-topic', createdAt: Date.now() - 137 },


  // Featured Videos (updated with new links)
  { 
    id: 'v-1', 
    name: 'The Messianic Vision | חזון הגאולה', 
    type: 'file', 
    parentId: 'f-videos', 
    content: '<p>Exploring the profound vision of the Messianic era as described by the sages and mystical texts.</p>', 
    contentType: 'video', 
    url: 'https://www.youtube.com/watch?v=0TDyuTfvBhk&list=PLYTqRxW76j8DexSCaC7of4e0xsW42kXIR', 
    createdAt: Date.now() - 5 
  },
  { 
    id: 'v-2', 
    name: 'Anticipating Redemption | ציפייה לישועה', 
    type: 'file', 
    parentId: 'f-videos', 
    content: '<p>Understanding the daily mitzvah of anticipating the Redemption and its practical application in our generation.</p>', 
    contentType: 'video', 
    url: 'https://www.youtube.com/watch?v=yw9W78m5vmE&list=PLYTqRxW76j8DexSCaC7of4e0xsW42kXIR&index=2&pp=iAQB', 
    createdAt: Date.now() - 6 
  },
  { 
    id: 'v-3', 
    name: 'The World of Resurrection | עולם התחייה', 
    type: 'file', 
    parentId: 'f-videos', 
    content: '<p>Delving into the mystical teachings about the World of Resurrection and its connection to our present service.</p>', 
    contentType: 'video', 
    url: 'https://www.youtube.com/watch?v=YckeRM72uzY&list=PLYTqRxW76j8DexSCaC7of4e0xsW42kXIR&index=3&pp=iAQB', 
    createdAt: Date.now() - 7 
  },
  { 
    id: 'v-4', 
    name: 'Preparing for the Messianic Era | הכנות לימות המשיח', 
    type: 'file', 
    parentId: 'f-videos', 
    content: '<p>Practical guidance on how to prepare ourselves and our communities for the imminent arrival of the Messianic era.</p>', 
    contentType: 'video', 
    url: 'https://www.youtube.com/watch?v=Q2976qXphKU&list=PLYTqRxW76j8DexSCaC7of4e0xsW42kXIR&index=4&pp=iAQB', 
    createdAt: Date.now() - 8 
  },
  { 
    id: 'v-5', 
    name: 'The Geulah Process | תהליך הגאולה', 
    type: 'file', 
    parentId: 'f-videos', 
    content: '<p>A comprehensive overview of the stages and processes leading to the ultimate Redemption.</p>', 
    contentType: 'video', 
    url: 'https://www.youtube.com/watch?v=R7sNI5JvU5M&list=PLYTqRxW76j8DexSCaC7of4e0xsW42kXIR&index=5&pp=iAQB', 
    createdAt: Date.now() - 9 
  },

  // Note Entry (existing)
  { 
    id: 'note-synagogues-israel', 
    name: 'Future Synagogues in Israel | בתי כנסיות שבבבל עתידים שיקבעו בארץ ישראל', 
    type: 'file', 
    parentId: 'f-notes', 
    content: ` 
      <div dir="rtl" class="text-right">
        <p class="mb-6 opacity-60">בס"ד</p>
        <h2 class="text-3xl font-bold mb-8">בענין בתי כנסיות ובתי מדרשות שבבבל שעתידים שיקבעו בארץ ישראל</h2>
        <p class="mb-6">בגמרא מסכת מגילה כט, א כתיב: תניא רבי אלעזר הקפר אומר, עתידים בתי כנסיות ובתי מדרשות שבבבל שיקבעו בארץ ישראל, שנאמר (ירמיה מו, יח) כי כתבור בהרים וככרמל בים יבוא.</p>
        <div class="space-y-6 text-xl leading-relaxed opacity-90">
          <p>והלא דברים קל וחומר, ומה תבור וככרמל שלא באו אלא לפי שעה ללמוד תורה, נקבעו בארץ ישראל, בתי כנסיות ובתי מדרשות שקורין ומרביצין בהם תורה, על אחת כמה וכמה.</p>
          <p><strong>השיטות השונות בזה:</strong></p>
          <ul class="list-disc pr-6 space-y-4">
            <li><strong>שיטת המהר"ם שיק וסיעתו:</strong> שהבנינים ביחד עם הקרקע יקבעו בארץ ישראל.</li>
            <li><strong>שיטת אליה רבה (סימן קנ"א):</strong> עכ"פ יש לומר שאף שהקרקע תקבע בארץ ישראל, אולי יהיה להם רק קדושת ארץ ישראל ולא קדושת בית הכנסת.</li>
            <li><strong>שיטת נתיב חיים:</strong> שיקבעו בארץ ישראל בשיטת המהר"ם וגם יבוא ממש הבית להיות כנסייה.</li>
            <li><strong>שיטת הרבי מליובאוויטש (קונטרס בית רבינו שבבבל):</strong> מבאר שהענין בזה הוא חזרת השכינה מאותם בתי כנסיות לארץ ישראל, וקדושתם של בתי כנסיות אלו תשאר קבועה ונצחית.</li>
          </ul>
          <p class="mt-8 font-bold text-2xl">ויה"ר שנזכה לקיום כל היעודים תומ"י ממש בחסד וברחמים!</p>
        </div>
      </div>
    `, 
    contentType: 'text', 
    createdAt: Date.now() - 41 
  },

  // DOCX Files - ערכים, עיונים, והערות בעניני גאולה ומשיח
  { id: 'file-magilat-chanukah', name: 'Megilat Chanukah | מגילת חנוכה לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 140 },
  { id: 'file-vilachom-milchemet', name: 'And He Shall Wage the Wars of G-d | וילחום מלחמת ה\'', type: 'file', parentId: 'sf-rambam-11-h4', content: '', contentType: 'text', createdAt: Date.now() - 141 },
  { id: 'file-pib-reish-halacha-b', name: 'Chapter 12, Beginning of Halacha 2 | פי"ב ריש הלכה ב\'', type: 'file', parentId: 'sf-rambam-12-h2', content: '', contentType: 'text', createdAt: Date.now() - 142 },
  { id: 'file-leatid-lavo-kulo-hatov', name: 'In the Future, All Good and Beneficent | לעתיד לבוא כולו הטוב והמטיב (פסחים נ, א)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 143 },
  { id: 'file-atid-gavriel-laasot', name: 'Gabriel Will Hunt Leviathan | עתיד גבריאל לעשות קניגיא עם לויתן (בבא בתרא עד, ב)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 144 },
  { id: 'file-ein-hagaliyot-mitkanesot-emunah', name: 'Exiles Gathered by Faith | אין הגליות מתכנסות אלא בשכר אמונה', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 145 },
  { id: 'file-kol-hazahir-mitzvat-tzitzit', name: 'He Who is Careful with Tzitzit | כל הזהיר במצות ציצית זוכה ומשמשין לו ב\' אלפים וח\' מאות עבדים', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 146 },
  { id: 'file-atidin-tzadikim-sheyachyu', name: 'Righteous Will Revive the Dead | עתידין צדיקים שיחיו את המתים (פסחים סח, א)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 147 },
  { id: 'file-teatrayot-karkasiyot-edom-1', name: 'Theaters and Circuses in Edom (1) | תראטריות וקרקסיות שבאדום (מגילה ו, א)(1)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 148 },
  { id: 'file-al-chomotayich-yerushalayim', name: 'On Your Walls, Jerusalem | על חומותיך ירושלים הפקדתי שומרים (מנחות פז, א)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 149 },
  { id: 'file-af-bechutz-laaretz', name: 'Even Outside Israel | אף בחוץ לארץ צריך לומר כן מפני שעתידים להתגייר (ברכות נז, ב)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 150 },
  { id: 'file-atidin-batei-knesiyot-bavel', name: 'Synagogues in Babylon to Israel | עתידין בתי כנסיות ובתי מדרשות שבבבל, שיקבעו בארץ ישראל (מגילה כט, א)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 151 },
  { id: 'file-atid-ani-litet-lahem', name: 'I Will Give Them That Weapon | עתיד אני ליתן להם לישראל אותו זיין שנוטל מהם בחורב', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 152 },
  { id: 'file-ein-hagaliyot-mitkanesot-mishnayot', name: 'Exiles Gathered by Mishnayot | אין הגליות מתכנסות אלא בזכות המשניות', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 153 },
  { id: 'file-hachzarat-haketarim', name: 'Return of Crowns | החזרת הכתרים שקשרו לישראל בשעה שהקדימו נעשה לנשמע', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 154 },
  { id: 'file-ein-ben-david-ba-prota', name: 'Son of David Comes When Coin Ends | אין בן דוד בא עד שתכלה פרוטה מן הכיס', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 155 },
  { id: 'file-venatati-lachem-lev-basar', name: 'I Will Give You a Heart of Flesh | ונתתי לכם לב בשר (ירושלמי יומא פרק ד\' הלכה א\')', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 156 },
  { id: 'file-hosafat-arei-miklat', name: 'Adding Cities of Refuge | הוספת ערי מקלט לע"ל', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 157 },
  { id: 'file-atid-hakadosh-baruch-hu-lehosif', name: 'G-d Will Add to Jerusalem | עתיד הקב"ה להוסיף על ירושלים עד שהסוס רץ ומציל', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 158 },
  { id: 'file-seforim-moshiach-basics', name: 'Basics | כללי', type: 'file', parentId: 'sf-seforim-basics', content: '', contentType: 'text', createdAt: Date.now() - 159 },
  { id: 'file-seforim-moshiach-third-beit-hamikdash', name: 'Third Beis Hamikdosh | בית המקדש השלישי', type: 'file', parentId: 'sf-seforim-third-beit-hamikdash', content: '', contentType: 'text', createdAt: Date.now() - 160 },
  { id: 'file-english-moshiach-websites', name: 'English Moshiach Websites', type: 'file', parentId: 'f-seforim', content: '', contentType: 'link', url: 'https://moshiach.com', createdAt: Date.now() - 161 },
  { id: 'file-torah-shebeal-peh-hevel', name: 'Oral Torah is Nothing Compared to Moshiach\'s Torah | תורה שבעוה"ז הבל לגבי תורתו של משיח', type: 'file', parentId: 'sf-concepts-new-torah', content: '', contentType: 'text', createdAt: Date.now() - 162 },
  { id: 'file-torah-chadasha-meiti-tetzei', name: 'New Torah Will Emerge From Me | תורה חדשה מאתי תצא', type: 'file', parentId: 'sf-concepts-new-torah', content: '', contentType: 'text', createdAt: Date.now() - 163 },
  { id: 'file-tefilah-al-techiyat-hametim', name: 'Prayer for Resurrection of the Dead | תפילה על תחיית המתים', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 164 },
  { id: 'file-seforim-moshiach-kabbalah', name: 'Kabbalah | ספרי קבלה על משיח', type: 'file', parentId: 'sf-seforim-kabbalah', content: '', contentType: 'text', createdAt: Date.now() - 165 },
  { id: 'file-seforim-moshiach-midrashim', name: 'Midrashim | מדרשי חז"ל', type: 'file', parentId: 'sf-seforim-midrashim', content: '', contentType: 'text', createdAt: Date.now() - 166 },
  { id: 'file-reishit-hagez', name: 'First of the Fleece | ראשית הגז לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 167 },
  { id: 'file-dinei-peirot-haaretz', name: 'Laws of Fruits of the Land | דיני פירות הארץ לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 168 },
  { id: 'file-uvoneh-hamikdash', name: 'And He Shall Build the Temple | ובונה המקדש', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 169 },
  { id: 'file-mitzvot-yovel', name: 'Mitzvah of Yovel | מצות יובל לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 170 },
  { id: 'file-kechol-mitzvatam', name: 'According to All Their Commandments | ככל מצותן האמורה בתורה', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 171 },
  { id: 'file-af-bearei-miklat', name: 'Even in Cities of Refuge | אף בערי מקלט הוא אומר', type: 'file', parentId: 'sf-rambam-11-h2', content: '', contentType: 'text', createdAt: Date.now() - 172 },
  { id: 'file-isha-meuberet-techiyat-hametim', name: 'Pregnant Woman in Resurrection | אשה מעוברת בתחיית המתים', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 173 },
  { id: 'file-veosin-shmitin-veyovlot-kechol', name: 'They Will Observe Shmitah and Yovel | ועושין שמיטין ויובלות ככל מצותן האמורה בתורה', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 174 },
  { id: 'file-vechozrin-kol-hamishpatim-a', name: 'All Judgments Return (A) | וחוזרין כל המשפטים בימיו כשהיו מקודם (א)', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 175 },
  { id: 'file-vechozrin-kol-hamishpatim-b', name: 'All Judgments Return (B) | וחוזרין כל המשפטים בימיו כשהיו מקודם (ב)', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 176 },
  { id: 'file-vechozrin-kol-hamishpatim', name: 'All Judgments Return | וחוזרין כל המשפטים', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 177 },
  { id: 'file-atida-eretz-yisrael-shetotzi-gluskaot-tkufa', name: 'Israel Will Produce Gluskaot - Era | עתידה א"י שתוציא גלוסקאות - באיזה תקופה, ובשיטת הרמב"ם בזה', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 178 },
  { id: 'file-vechozrin-kol-hamishpatim-biyamav', name: 'All Judgments Return in His Days | וחוזרין כל המשפטים בימיו', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 179 },
  { id: 'file-veosin-shmitin-veyovlot', name: 'They Will Observe Shmitah and Yovel | ועושין שמיטין ויובלות', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 180 },
  { id: 'file-shleimut-hatorah', name: 'Completeness of Torah | שלימות התורה לע"ל', type: 'file', parentId: 'sf-concepts-new-torah', content: '', contentType: 'text', createdAt: Date.now() - 181 },
  { id: 'file-mispar-hakelim-bebeit-hamikdash', name: 'Number of Vessels in Third Temple | מספר הכלים בביהמ"ק השלישי', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 182 },
  { id: 'file-geder-hageulah-biyat-moshiach-b', name: 'Definition of Redemption & Moshiach (B) | גדר הגאולה וביאת המשיח עפ"י שיטת הרמב"ם (ב)', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 183 },
  { id: 'file-mahu-geulah-amitit', name: 'What is True and Complete Redemption | מהו גאולה האמיתית והשלימה', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 184 },
  { id: 'file-veyitaken-et-haolam-kulo-leavod', name: 'He Will Repair the Entire World to Serve G-d | ויתקן את העולם כולו לעבוד את ה\' ביחד', type: 'file', parentId: 'sf-rambam-11-h4', content: '', contentType: 'text', createdAt: Date.now() - 185 },
  { id: 'file-im-leatid-nitzterach-chatat', name: 'Will We Need Sin Offering in Future? | האם לע"ל נצטרך להביא חטאת, על עבירות שנעשו בשוגג בזמן הזה', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 186 },
  { id: 'file-isur-nidah', name: 'Prohibition of Niddah | איסור נדה לע"ל', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 187 },
  { id: 'file-seforim-moshiach-classics', name: 'Classics | ספרי יסוד', type: 'file', parentId: 'sf-seforim-classics', content: '', contentType: 'text', createdAt: Date.now() - 188 },
  { id: 'file-toelet-hatzipui', name: 'Benefit of Anticipating Redemption | תועלת הציפוי להגאולה', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 189 },
  { id: 'file-melech-moshiach-kenasi-hasanhedrin', name: 'Moshiach as Nasi of Sanhedrin | מלך המשיח כנשיא הסנהדרין', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 190 },
  { id: 'file-makrivin-korbanot', name: 'Offering Sacrifices | מקריבין קרבנות', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 191 },
  { id: 'file-asiyat-keli-beit-hamikdash', name: 'Making Temple Vessels | עשיית כלי ביהמ"ק השלישי לשיטת הרמב"ם', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 192 },
  { id: 'file-kibud-av-vaem-techiyat-hametim', name: 'Honoring Parents After Resurrection | כיבוד אב ואם לאחרי תחיית המתים', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 193 },
  { id: 'file-atida-eretz-yisrael-shetotzi-gluskaot-dirah', name: 'Israel Will Produce Gluskaot - Dwelling | עתידה א"י שתוציא גלוסקאות - הקשר עם דירה בתחתונים', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 194 },
  { id: 'file-matanot-aniyim', name: 'Gifts to the Poor | מתנות עניים לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 195 },
  { id: 'file-leyoshna-lememshala-rishona-a', name: 'To Its Former Rule (A) | ליושנה לממשלה הראשונה (א)', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 196 },
  { id: 'file-chiyuv-trumot-maaserot', name: 'Obligation of Terumot and Maaserot | חיוב תרומות ומעשרות בפירות שיצמחו בדרך נס לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 197 },
  { id: 'file-gluskaot-vkeli-milat', name: 'Gluskaot and Keli Milat | גלוסקאות וכלי מילת לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 198 },
  { id: 'file-keli-milat', name: 'Keli Milat | כלי מילת לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 199 },
  { id: 'file-atida-chita-shetitmar', name: 'Wheat Will Grow Like Palm Tree | עתידה חטה שתתמר כדקל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 200 },
  { id: 'file-matanot-kehuna', name: 'Priestly Gifts | מתנות כהונה לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 201 },
  { id: 'file-bitul-neviim-ketuvim-a', name: 'Abolition of Prophets & Writings (A) | ביטול הנביאים וכתובים לע"ל (א)', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 202 },
  { id: 'file-bitul-neviim-ketuvim-b', name: 'Abolition of Prophets & Writings (B) | ביטול הנביאים וכתובים לע"ל (ב)', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 203 },
  { id: 'file-limud-nigleh-detorah-shket-a', name: 'Study of Revealed Torah in Tranquility (A) | לימוד נגלה דתורה בשקו"ט לע"ל (א)', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 204 },
  { id: 'file-limud-nigleh-detorah-shket-b', name: 'Study of Revealed Torah in Tranquility (B) | לימוד נגלה דתורה בשקו"ט לע"ל (ב)', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 205 },
  { id: 'file-geder-hageulah-biyat-moshiach-a', name: 'Definition of Redemption & Moshiach (A) | גדר הגאולה וביאת המשיח עפ"י שיטת הרמב"ם (א)', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 206 },
  { id: 'file-hiluk-peulot-eliyahu-moshiach-a', name: 'Difference in Actions of Elijah & Moshiach (A) | החילוק בין פעולות אליהו הנביא ומלך המשיח (א)', type: 'file', parentId: 'sf-concepts-eli', content: '', contentType: 'text', createdAt: Date.now() - 207 },
  { id: 'file-yichus-bnei-yisrael', name: 'Genealogy of Israel by Moshiach | ייחוס בני ישראל ע"י מלך המשיח', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 208 },
  { id: 'file-zman-rosh-hashana-lailanot', name: 'Time of Rosh Hashanah for Trees | זמן ראש השנה לאילנות לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 209 },
  { id: 'file-halacha-lemoshe-misinai-eliyahu', name: 'Halacha L\'Moshe MiSinai Regarding Elijah | הלכה למשה מסיני אודות אלי\' הנביא', type: 'file', parentId: 'sf-concepts-eli', content: '', contentType: 'text', createdAt: Date.now() - 210 },
  { id: 'file-hafecha-hataaniyot', name: 'Transformation of Fasts | הפיכת התעניות לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 211 },
  { id: 'file-bituyei-hatzipui', name: 'Expressions of Anticipation for Redemption | ביטויי הציפוי לגאולה', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 212 },
  { id: 'file-techiyat-hametim-eliyahu-moshiach', name: 'Resurrection by Elijah or Moshiach | תחיית המתים ע"י אליהו או משיח', type: 'file', parentId: 'sf-concepts-eli', content: '', contentType: 'text', createdAt: Date.now() - 213 },
  { id: 'file-im-yihyu-shvutim-derabanan', name: 'Will There Be Rabbinic Prohibitions? | האם יהי\' שבותים דרבנן לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 214 },
  { id: 'file-zman-biyat-eliyahu-gog-umagog-a', name: 'Time of Elijah & Gog U\'Magog (A) | זמן ביאת אלי\' ומלחמת גוג ומגוג - א', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 215 },
  { id: 'file-biyat-moshiach-beshabbat', name: 'Moshiach Comes on Shabbat | ביאת משיח בשבת', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 216 },
  { id: 'file-gadol-yom-kibutz-galiyot', name: 'Great is Day of Gathering Exiles | גדול יום קיבוץ גליות כיום שנבראו בו שמים וארץ', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 217 },
  { id: 'file-hiluk-sugnon-harambam', name: 'Difference in Rambam\'s Style | חילוק סגנון הרמב"ם בין פי"א לפי"ב', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 218 },
  { id: 'file-ikvata-dimshicha', name: 'Era of Ikveta D\'Mshicha | בענין תקופת עקבתא דמשיחא', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 219 },
  { id: 'file-dvarim-stumim-hem', name: 'They Are Hidden Matters | דברים סתומים הם', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 220 },
  { id: 'file-seder-simanei-moshiach', name: 'Order of Moshiach\'s Signs | סדר סימני משיח בהרמב"ם', type: 'file', parentId: 'sf-rambam-11-h4', content: '', contentType: 'text', createdAt: Date.now() - 221 },
  { id: 'file-moshiach-videos', name: 'Moshiach Videos', type: 'file', parentId: 'f-videos', content: '', contentType: 'text', createdAt: Date.now() - 222 },
  { id: 'file-moshiach-bechol-dor-bemeshech', name: 'Moshiach in Every Generation | משיח בכל דור - במשך הדורות', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 223 },
  { id: 'file-biyat-eliyahu-leil-pesach', name: 'Elijah Comes on Pesach Night | ביאת אליהו הנביא בליל פסח', type: 'file', parentId: 'sf-concepts-eli', content: '', contentType: 'text', createdAt: Date.now() - 224 },
  { id: 'file-yaamod-navi-leyasher-yisrael', name: 'A Prophet Will Arise to Straighten Israel | יעמוד נביא ליישר ישראל', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 225 },
  { id: 'file-hal-melachim-pib-hab', name: 'Laws of Kings Chapter 12 Halacha 2 | הל\' מלכים פי"ב ה"ב', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 226 },
  { id: 'file-yeudim-gashmiim-klali', name: 'Physical Prophecies - General | יעודים גשמיים - כללי', type: 'file', parentId: 'sf-destinies-general', content: '', contentType: 'text', createdAt: Date.now() - 227 },
  { id: 'file-hasarat-hacholi', name: 'Removal of Illness | הסרת החולי לע"ל ע"פ שיטת הרנב"ם', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 228 },
  { id: 'file-teatrayot-karkasiyot-edom', name: 'Theaters and Circuses in Edom | תראטריות וקרקסיות שבאדום (מגילה ו, א)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 229 },
  { id: 'file-binyan-beit-hamikdash-shlishi', name: 'Building the Third Temple | בנין בית המקדש השלישי', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 230 },
  { id: 'file-seforim-moshiach-tanach', name: 'Tanach | תורה שבכתב', type: 'file', parentId: 'sf-seforim-tanach', content: '', contentType: 'text', createdAt: Date.now() - 231 },
  { id: 'file-seforim-moshiach-in-order-alef-beis', name: 'In Order of Alef Beis | In order of Alef beis', type: 'file', parentId: 'f-seforim', content: '', contentType: 'text', createdAt: Date.now() - 232 },
  { id: 'file-inyan-hakitzin-hashonim', name: 'Matter of Various Ends | בענין הקיצין השונים', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 233 },
  { id: 'file-chaluka-chadasha', name: 'New Division | חלוקה חדשה לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 234 },
  { id: 'file-mehirut-tzmichat-hapeirot', name: 'Speed of Fruit Growth | מהירות צמיחת הפירות לע"ל', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 235 },
  { id: 'file-bechira-chofshit', name: 'Free Will | בחירה חפשית לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 236 },
  { id: 'file-lama-sheino-mechakeh', name: 'Why One Who Does Not Await Moshiach is a Heretic | למה מי שאינו מחכה לביאת המשיח הוא כופר', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 237 },
  { id: 'file-im-yihyu-harim', name: 'Will There Be Mountains? | האם יהי\' הרים לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 238 },
  { id: 'file-shitat-hachafetz-chaim', name: 'Chafetz Chaim\'s View on "I Await Him Daily" | שיטת החפץ חיים באחכה לו בכל יום שיבוא', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 239 },
  { id: 'file-im-yitmahameha-chakeh-lo', name: 'If He Delays, Await Him | אם יתמהמה חכה לו', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 240 },
  { id: 'file-hatzipui-lebiat-moshiach-tadir', name: 'Constant Anticipation for Moshiach | הציפוי לביאת המשיח תדיר', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 241 },
  { id: 'file-atida-eretz-yisrael-shetotzi-gluskaot-keli-milat', name: 'Israel Will Produce Gluskaot & Keli Milat | עתידה א"י שתוציא גלוסקאות וכלי מילת', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 242 },
  { id: 'file-binyan-beit-hamikdash-bazman-hazeh', name: 'Building the Temple in Our Time | בנין בית המקדש בזמן הזה', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 243 },
  { id: 'file-yeiti-veachminiya', name: 'I Will Come and See Him | ייתי ואחמיניה', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 244 },
  { id: 'file-likut-atidin-batei-knesiyot', name: 'Collection: Synagogues in Babylon to Israel | ליקוט: עתידין בתי כנסיות ובתי מדרשות שבבבל, שיקבעו בארץ ישראל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 245 },
  { id: 'file-ein-mekablin-gerim', name: 'No Converts in Messianic Era | בענין אין מקבלין גרים לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 246 },
  { id: 'file-kulam-gerim-grurim', name: 'All Are Drawn Converts | כולם גרים גרורים הם לעתיד לבא (עבודה זרה כד, א)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 247 },
  { id: 'file-veamdu-zarim-verau-tzonchem', name: 'Strangers Will Stand and Tend Your Flocks | ועמדו זרים ורעו צאנכם וגו\'', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 248 },
  { id: 'file-umot-haolam-leatid-lavo', name: 'Nations of the World in Future | אומות העולם לע"ל - ועמדו זרים וגו\'', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 249 },
  { id: 'file-ahava-veyirah-utefilah', name: 'Love, Awe, and Prayer | אהבה ויראה ותפילה לע"ל', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 250 },
  { id: 'file-techiyat-hametim-liydei-eliyahu', name: 'Resurrection by Elijah - Rambam\'s View | תחיית המתים לידי אליהו - לשיטת הרמב"ם', type: 'file', parentId: 'sf-concepts-eli', content: '', contentType: 'text', createdAt: Date.now() - 251 },
  { id: 'file-hatorah-eida-alav', name: 'The Torah Testified About Him | התורה העידה עליו', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 252 },
  { id: 'file-atida-isha-shetelid-bechol-yom', name: 'Woman Will Give Birth Daily | עתידה אשה שתלד בכל יום', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 253 },
  { id: 'file-gil-meah-shana-lechiyuvim', name: 'Age of 100 for Obligations | גיל מאה שנה לחיובים לע"ל', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 254 },
  { id: 'file-bayom-hahu-yechei-ish-aglat-bakar', name: 'On That Day, a Man Will Raise a Calf | ביום ההוא יחי\' איש עגלת בקר וגו\'', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 255 },
  { id: 'file-ein-mekablin-gerim-limot-hamoshiach', name: 'No Converts in Days of Moshiach | אין מקבלין גרים לימות המשיח', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 256 },
  { id: 'file-atidim-ilanei-srak-laasot-peirot', name: 'Barren Trees Will Bear Fruit | עתידים אילני סרק לעשות פירות לע"ל', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 257 },
  { id: 'file-heverot-beinyanei-beit-hamikdash', name: 'Notes on Third Temple | הערות בעניני בית המקדש השלישי', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 258 },
  { id: 'file-mati-hitchelu-lehitpalel', name: 'When Did Prayer for Redemption Begin? | מתי התחילו להתפלל על הגאולה', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 259 },
  { id: 'file-shalom-veachdut', name: 'Peace and Unity | שלום ואחדות לע"ל', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 260 },
  { id: 'file-hakravat-korbanot-acharei-biyat-moshiach', name: 'Offering Sacrifices Only After Moshiach | הקרבת קרבנות רק לאחר ביאת המשיח', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 261 },
  { id: 'file-inyan-eliyahu-nevi-al-pi-chasidut', name: 'Elijah the Prophet According to Chassidut | ענין אלי\' הנביא לע"ל ע"פ חסידות', type: 'file', parentId: 'sf-concepts-eli', content: '', contentType: 'text', createdAt: Date.now() - 262 },
  { id: 'file-eliyahu-nevi-bechinat-daat', name: 'Elijah the Prophet - Aspect of Daat | אליהו הנביא בחי\' דעת', type: 'file', parentId: 'sf-concepts-eli', content: '', contentType: 'text', createdAt: Date.now() - 263 },
  { id: 'file-achakeh-lo-bechol-yom-hayom', name: 'I Await Him Daily - Today | אחכה לו בכל יום שיבוא - היום', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 264 },
  { id: 'file-anu-lama-machkin', name: 'Why Do We Wait? To Receive Reward | אנו למה מחכין? לקבל שכר (סנהדרין צז, ב)', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 265 },
  { id: 'file-biyat-eliyahu-lifnei-yom-hashem', name: 'Elijah Comes Before the Great Day of G-d | ביאת אליהו לפני "יום ה\' הגדול והנורא"', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 266 },
  { id: 'file-yeudei-halida', name: 'Prophecies of Birth | יעודי הלידה לעתיד לבוא', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 267 },
  { id: 'file-yeudei-peirot-haaretz-vehaailan', name: 'Prophecies of Fruits of Land & Tree | יעודי פירות הארץ והאילן לע"ל', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 268 },
  { id: 'file-zman-techiyat-hametim', name: 'Time of Resurrection of the Dead | זמן תחיית המתים', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 269 },
  { id: 'file-yesodot-chiyuv-haemunah', name: 'Foundations of Obligation to Believe in Moshiach | יסודות חיוב האמונה בביאת המשיח', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 270 },
  { id: 'file-ashirut-bnei-yisrael', name: 'Wealth of Israel | עשירות בני ישראל לע"ל', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 271 },
  { id: 'file-achakeh-lo-bechol-yom-zman-haketz', name: 'I Await Him Daily & Time of End | אחכה לו בכל יום שיבוא וזמן הקץ', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 272 },
  { id: 'file-veyitaken-et-haolam-kulo-domem', name: 'He Will Repair the Entire World - Inanimate, Plant, Animal, Speaking | ויתקן את העולם כולו - דומם צומח חי מדבר', type: 'file', parentId: 'sf-rambam-11-h4', content: '', contentType: 'text', createdAt: Date.now() - 273 },
  { id: 'file-hareini-nazir', name: 'I Am a Nazir on Day Son of David Comes | הריני נזיר ביום שבן דוד בא', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 274 },
  { id: 'file-geder-hatzipui', name: 'Definition of Anticipation for Moshiach | גדר הציפוי לביאת המשיח', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 275 },
  { id: 'file-leyoshna-lememshala-rishona-b', name: 'To Its Former Rule (B) | ליושנה לממשלה הראשונה (ב)', type: 'file', parentId: 'sf-rambam-11-h1', content: '', contentType: 'text', createdAt: Date.now() - 276 },
  { id: 'file-shleimut-hamitzvot', name: 'Completeness of Mitzvot | שלימות המצוות', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 277 },
  { id: 'file-lishma-yibaneh-lo-chayshinan', name: 'We Are Not Concerned Lest It Be Built | לשמא יבנה לא חיישינן', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 278 },
  { id: 'file-yesodot-hamachloket-rambam-ramban', name: 'Foundations of Dispute Between Rambam & Ramban | יסודות המחלוקת בין הרמב"ם ורמב"ן בענין עולם הבא ותחיית המתים', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 279 },
  { id: 'file-biyat-moshiach-bechodesh-nisan', name: 'Moshiach Comes in Month of Nisan | ביאת המשיח בחודש ניסן', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 280 },
  { id: 'file-halachot-melachim-pib-ha', name: 'Laws of Kings Chapter 12 Halacha 1 | הלכות מלכים פיב הא', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 281 },
  { id: 'file-zman-biyat-eliyahu-gog-umagog-b', name: 'Time of Elijah & Gog U\'Magog (B) | זמן ביאת אלי\' ומלחמת גוג ומגוג - ב', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 282 },
  { id: 'file-biyat-eliyahu-lifnei-yom-hashem-mahadorah', name: 'Elijah Comes Before the Great Day of G-d - Second Edition | ביאת אליהו לפני "יום ה\' הגדול והנורא" - מהדורה שני\'', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 283 },
  { id: 'file-leyasher-yisrael-ulehachin-libam', name: 'To Straighten Israel and Prepare Their Hearts | ליישר ישראל ולהכין לבם', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 284 },
  { id: 'file-ofen-kibutz-galiyot', name: 'Manner of Gathering Exiles | אופן קיבוץ גליות - עם ענני שמיא ועוד ביאורים', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 285 },
  { id: 'file-dvar-malchus-2', name: 'Dvar Malchus 2', type: 'file', parentId: 'f-seforim', content: '', contentType: 'text', createdAt: Date.now() - 286 },
  { id: 'file-reshimat-sefarim', name: 'List of Books on Redemption | רשימת ספרים בעניני גאולה ומשיח', type: 'file', parentId: 'f-seforim', content: '', contentType: 'text', createdAt: Date.now() - 287 },
  { id: 'file-bitul-hayeitzer-hara', name: 'Abolition of Evil Inclination | ביטול היצר הרע לע"ל', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 288 },
  { id: 'file-lo-yeda-adam-eich-yihyu', name: 'No Man Knows How They Will Be | לא ידע אדם איך יהיו עד שיהיו', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 289 },
  { id: 'file-im-yomar-lecha-adam', name: 'If a Man Says to You, Buy a Field | אם יאמר לך אדם קח שדה שוה אלף דינרים בדינר אחד, לא תקח', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 290 },
  { id: 'file-hiluk-peulot-eliyahu-moshiach-b', name: 'Difference in Actions of Elijah & Moshiach (B) | החילוק בין פעולות אליהו הנביא ומלך המשיח (ב)', type: 'file', parentId: 'sf-concepts-eli', content: '', contentType: 'text', createdAt: Date.now() - 291 },
  { id: 'file-teshbi-yitaretz-kushiyot', name: 'Tishbi Will Resolve Difficulties | תשבי יתרץ קושיות ואבעיות', type: 'file', parentId: 'sf-concepts-eli', content: '', contentType: 'text', createdAt: Date.now() - 292 },
  { id: 'file-im-david-hamelech-yachol-lihiyot-moshiach', name: 'Can King David Be Moshiach? | האם דוד המלך יכול להיות משיח?', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 293 },
  { id: 'file-rabbi-akiva', name: 'Rabbi Akiva', type: 'file', parentId: 'f-notes', content: '', contentType: 'text', createdAt: Date.now() - 294 },
  { id: 'file-hochachat-harambam-merabbi-akiva', name: 'Rambam\'s Proof from Rabbi Akiva | הוכחת הרמב"ם מרבי עקיבא שמשיח אין צריך לעשות נסים', type: 'file', parentId: 'sf-rambam-11-h3', content: '', contentType: 'text', createdAt: Date.now() - 295 },
  { id: 'file-shitat-harambam-beigeret-techiyat-hametim', name: 'Rambam\'s View in Letter on Resurrection | שיטת הרמב"ם באגרת תחיית המתים, לפי הבנת הרבי', type: 'file', parentId: 'sf-rambam-12', content: '', contentType: 'text', createdAt: Date.now() - 296 },
  { id: 'file-chiyuv-haemunah-bebiat-moshiach', name: 'Obligation to Believe in Moshiach | חיוב האמונה בביאת המשיח', type: 'file', parentId: 'sf-concepts-belief', content: '', contentType: 'text', createdAt: Date.now() - 297 },
  { id: 'file-seder-vezman-kibutz-galiyot', name: 'Order and Time of Gathering Exiles | סדר וזמן קיבוץ גליות', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 298 },
  { id: 'file-mi-yelamed-hatorah-chadasha', name: 'Who Will Teach the New Torah? | מי יְלַמֵד התורה חדשה?', type: 'file', parentId: 'sf-concepts-new-torah', content: '', contentType: 'text', createdAt: Date.now() - 299 },
  { id: 'file-limud-hatorah-inyanim-bilti-ratzuyim', name: 'Study of Torah Regarding Undesirable Matters | לימוד התורה אודות ענינים בלתי רצויים לע"ל', type: 'file', parentId: 'sf-concepts-new-torah', content: '', contentType: 'text', createdAt: Date.now() - 300 },
  { id: 'file-kategoriyah-betalmidei-chachamim', name: 'Accusation Against Torah Scholars | קטיגוריא בתלמידי חכמים', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 301 },
  { id: 'file-dchikat-haketz', name: 'Pushing the End | דחיקת הקץ', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 302 },
  { id: 'file-shleimut-briut-haguf', name: 'Completeness of Body Health | שלימות בריאות הגוף לע"ל', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 303 },
  { id: 'file-shleimut-hamitzvot-al-pi-chasidut', name: 'Completeness of Mitzvot According to Chassidut | שלימות המצוות ע"פ חסידות - כמצות רצונך', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 304 },
  { id: 'file-chet-uteshuva-veyom-hakippurim', name: 'Sin, Repentance, and Yom Kippur | חטא ותשובה ויום הכפורים לע"ל', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 305 },
  { id: 'file-af-yehudi-lo-yishar-bagalut', name: 'No Jew Will Remain in Exile | אף יהודי לא ישאר בגלות', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 306 },
  { id: 'file-ein-ben-david-ba-dag-lacholeh', name: 'Son of David Comes When Fish Not Found for Sick | אין בן דוד בא עד שיתבקש דג לחולה ולא ימצא', type: 'file', parentId: 'sf-sages-quotes', content: '', contentType: 'text', createdAt: Date.now() - 307 },
  { id: 'file-moshiach-bechol-dor', name: 'Moshiach in Every Generation | משיח בכל דור', type: 'file', parentId: 'f-concepts', content: '', contentType: 'text', createdAt: Date.now() - 308 },
  { id: 'file-arichut-yamim', name: 'Longevity | אריכות ימים לע"ל', type: 'file', parentId: 'f-destinies', content: '', contentType: 'text', createdAt: Date.now() - 309 },
];